spring:
  application:
    name: interview
  datasource:
    url: jdbc:mysql://localhost:3306/code_interview
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
